### ISSUE TITLE
[BUG] special characters 

### ISSUE THREAD

**Issue by Bhooty** [libDrive/libDrive#34]
Folder like # 
Or names with special characters like # is not working 
For example, #LIKE movie 
https://www.themoviedb.org/movie/632076-like

**Comment by eliasbenb** [comment]
Thank you for the report!

This issue was fixed 3 days ago in this commit https://github.com/libDrive/web/commit/f0d50084ceabcbc74c894205a135c2e18cc6cc86

You'll need to wait for the next version to see the changes though.

**Comment by Bhooty** [comment]
sir is it fixed in the latest release? or will be fixed in next release?

**Comment by eliasbenb** [comment]
> sir is it fixed in the latest release? or will be fixed in next release?

It has been fixed

**Comment by Bhooty** [comment]
Still error

**Comment by Bhooty** [comment]
Still Crashing

![photo_2021-08-06_20-47-28](https://user-images.githubusercontent.com/46019727/128528683-5c6051e0-dfc8-4f3a-baf7-8172ac2ebd20.jpg)

**Comment by eliasbenb** [comment]
> Still Crashing
> 
> ![photo_2021-08-06_20-47-28](https://user-images.githubusercontent.com/46019727/128528683-5c6051e0-dfc8-4f3a-baf7-8172ac2ebd20.jpg)

v1.3.10 just released, tell me if the issue still persists.
